name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.3"
      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Lint
        run: |
          black --check .
          isort --profile black .
      - name: Test
        run: |
          pytest -vv --cov=migaku_wiktionary
